<?php

/**
 * @file
 * A permission that controls if a user is allowed to change publishing status.
 */

/**
 * Implements hook_permission().
 */
function change_publishing_status_permission_permission() {
  return array(
    'change publishing status' => array(
      'title' => t('Change publishing status.'),
      'description' => t('If enabled, the user is allowed to change the publishing status of nodes.'),
    ),
    'update published nodes' => array(
      'title' => t('Edit published nodes.'),
      'description' => t('Expand the user’s node edit permissions to published nodes.'),
    ),
    'delete published nodes' => array(
      'title' => t('Delete published nodes.'),
      'description' => t('Expand the user’s node delete permissions to published nodes.'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 *
 * Disables and hides the submit button if permissions are insufficient for
 * publishing.
 */
function change_publishing_status_permission_form_node_form_alter(&$form, &$form_state, $form_id) {
  if (!user_access('change publishing status')) {
    $form['options']['status']['#disabled'] = TRUE;
    if (user_access('save draft')) {
      $form['actions']['#process'][] = 'change_publishing_status_permission_submit_access';
    }
  }
}

/**
 * Implements hook_node_access().
 *
 * Restricts editing and deleting of published nodes.
 */
function change_publishing_status_permission_node_access($node, $op, $account) {
  $restricted_op = in_array($op, ['update', 'delete']);
  $published = is_object($node) && $node->status;
  if ($published && $restricted_op && !user_access("$op published nodes", $account)) {
    return NODE_ACCESS_DENY;
  }
  return NODE_ACCESS_IGNORE;
}

/**
 * Implements hook_node_prepare().
 */
function change_publishing_status_permission_node_prepare($node) {
  if (empty($node->nid) && !user_access('change publishing status')) {
    $node->status = NODE_NOT_PUBLISHED;
  }
}

/**
 * Form process handler for node_form().
 *
 * Remove access to submit-buttons that will change the publishing status.
 *
 * @see change_publishing_status_permission_form_node_form_alter()
 */
function change_publishing_status_permission_submit_access(array $element, &$form_state, array $form) {
  $node = $form_state['node'];
  if ($node->status && isset($element['draft'])) {
    $element['draft']['#access'] = FALSE;
  }
  if (!$node->status && isset($element['submit'])) {
    $element['submit']['#access'] = FALSE;
  }
  return $element;
}
